# Generated by Django 4.0.6 on 2022-12-29 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telawat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.CharField(max_length=200, null=True)),
                ('ayat', models.CharField(max_length=200, null=True)),
                ('arruracy', models.CharField(max_length=200)),
                ('audio', models.FileField(null=True, upload_to='')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
