# Generated by Django 4.0.6 on 2022-12-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_telawat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telawat',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
