# Generated by Django 4.0.6 on 2023-01-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_telawat_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telawat',
            name='arruracy',
            field=models.CharField(default='Waiting', max_length=200),
        ),
    ]
