# Generated by Django 4.0.6 on 2023-01-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_telawat_arruracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telawat',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
